theme: minima
title: Instant People Learning
author: n3rdankit
email: erankit.sharma95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IPL is open source website which is abbreviated as Instant Peple
  Learning. Here we share our instants, experiences and learnings
  with all people.
# social links
twitter_username: n3rdankit # DO NOT include the @ character, or else the build will fail!
github_username:  n3rdankit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
